#这里使用的是yml的配置模式
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youyougou?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /**
  application:
    name: solr
  data:
    solr:
      host: http://127.0.0.1:8090/solr
server:
  port: 8092